export const CART_FETCH_PRODUCT = 'CART_FETCH_PRODUCT';
export const CART_SET_PRODUCT = 'CART_SET_PRODUCT';
export const CART_DEFAULT = 'CART_DEFAULT';
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT';
export const CART_ORDER = 'CART_ORDER';
