export const HOME_FETCH_PRODUCT = 'HOME_FETCH_PRODUCT';
export const HOME_SET_PRODUCT = 'HOME_SET_PRODUCT';
export const HOME_FIND_PRODUCT = 'HOME_FIND_PRODUCT';
export const HOME_DEFAULT = 'HOME_DEFAULT';
